### PR TITLE
fix(deps): update all dependencies

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR updates all dependencies in each of the examples (Angular, React, Svelte & Vue), including updating Cypress to ~~`13.4.0`~~ `13.6.1`. The `lockfileVersion` contained in the respective `package-lock.json` files is migrated from `2` to `3`.

It resolves vulnerabilities in the examples:

| Framework | Resolved Vulnerabilities                           |
| --------- | -------------------------------------------------- |
| Angular   | 9 vulnerabilities (5 moderate, 2 high, 2 critical) |
| React     | 2 vulnerabilities (1 moderate, 1 critical)         |
| Svelte    | 1 moderate severity vulnerability                  |
| Vue       | 1 moderate severity vulnerability                  |

Edit: A follow-on PR is now necessary to update to Angular 17, since in the meantime this is now supported by Cypress.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@jordanpowell88 

Is there any interest in this PR? By now it is also slightly out-of-date, however I don't want to put effort into updating it unless somebody will pick it up, then review and merge it.

The major reason for the PR is to resolve security vulnerabilities in the examples.

**Comment by jordanpowell88** [comment]
Hey @MikeMcC399 Sorry to keep you in flux on this. Yes I think we want to keep these up-to-date it just got lost in the shuffle. Can you go ahead and update to the most recent version (Angular 17, etc) and give me a ping?

**Comment by MikeMcC399** [comment]
@jordanpowell88 

I have updated this PR to latest versions according to the semver definitions in the respective `package.json` files.

- Updating to `vite@5` requires that Cypress support this version. See https://github.com/cypress-io/cypress/issues/28347. So therefore Vite is left using `v4`.
- I have prepared a separate PR to update to Angular `17`, which I will submit once this one is merged as base

**Review by jordanpowell88 — APPROVED** [review]

**Comment by jordanpowell88** [comment]
Thanks @MikeMcC399

**Pull request merged**
