### PR TITLE
ci: add GitHub Action CI workflow

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR adds the `.github/workflows/test.yml` workflow to test each of the quickstart apps using Cypress component testing:

1. [angular/my-awesome-app](https://github.com/cypress-io/component-testing-quickstart-apps/tree/main/angular/my-awesome-app)
1. [react/my-awesome-app](https://github.com/cypress-io/component-testing-quickstart-apps/tree/main/react/my-awesome-app)
1. [svelte/my-awesome-app](https://github.com/cypress-io/component-testing-quickstart-apps/tree/main/svelte/my-awesome-app)
1. [vue/my-awesome-app](https://github.com/cypress-io/component-testing-quickstart-apps/tree/main/vue/my-awesome-app)

This provides confidence of correctness when future changes are made to this repository.

The workflow makes use of [cypress-io/github-action](https://github.com/cypress-io/github-action).

### CODE REVIEW

**Comment by MikeMcC399** [comment]
This workflow ran successfully in run [5760595188](https://github.com/MikeMcC399/component-testing-quickstart-apps/actions/runs/5760595188)

image

**Comment by MikeMcC399** [comment]
@jordanpowell88 

Could you take a look? This repo is not part of the general triage process, so I don't know if anybody gets automatically notified.

**Review by jordanpowell88 — APPROVED** [review]
Thank you for doing this. Been waiting to do this for a while

**Comment by MikeMcC399** [comment]
@jordanpowell88 

> Thank you for doing this. Been waiting to do this for a while

My pleasure! Since I was submitting changes to the examples, I wanted to have an automated way of testing the changes, so I thought it was a good idea to set up CI.

Thank you for reviewing and merging in any case! 👏🏻

**Pull request merged**
